"use client";

import { useState, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X } from "lucide-react";
import Image from "next/image";
import { useScrollProgress } from "@/hooks/use-scroll-progress";
import { ScrollFrameCanvas } from "@/components/scroll-frame-canvas";

interface CaseStudy {
  brand: string;
  campaign: string;
  description: string;
  stats: { label: string; value: string }[];
  images: { src: string; alt: string; aspect: "landscape" | "square" | "story" }[];
}

const caseStudies: CaseStudy[] = [
  {
    brand: "Nike",
    campaign: "Own the Morning",
    description:
      "Cinematic urban running. Pre-dawn darkness, sodium streetlights, one runner, electric-orange Alphaflys.",
    stats: [
      { label: "Images", value: "5" },
      { label: "Formats", value: "3" },
      { label: "Cost", value: "£0.76" },
    ],
    images: [
      { src: "/portfolio/nike-1-landscape.jpg", alt: "Runner in underpass at dawn", aspect: "landscape" },
      { src: "/portfolio/nike-2-story.jpg", alt: "Runner portrait", aspect: "story" },
      { src: "/portfolio/nike-3-square.jpg", alt: "Alphafly splash", aspect: "square" },
      { src: "/portfolio/nike-4-square.jpg", alt: "Runner resting", aspect: "square" },
      { src: "/portfolio/nike-5-story.jpg", alt: "Golden hour", aspect: "story" },
    ],
  },
  {
    brand: "Ama Shea",
    campaign: "Whipped Butter",
    description:
      "Luxury skincare. Warm golden-amber lighting, botanical accents, perfect product consistency.",
    stats: [
      { label: "Images", value: "7" },
      { label: "Avg QA", value: "4.7/5" },
      { label: "Cost", value: "£1.42" },
    ],
    images: [
      { src: "/portfolio/ama-shea-1-square.jpg", alt: "Shea butter hero", aspect: "square" },
      { src: "/portfolio/ama-shea-2-square.jpg", alt: "Product with botanicals", aspect: "square" },
      { src: "/portfolio/ama-shea-3-square.jpg", alt: "Lifestyle shot", aspect: "square" },
      { src: "/portfolio/ama-shea-4-square.jpg", alt: "Ingredients", aspect: "square" },
      { src: "/portfolio/ama-shea-5-square.jpg", alt: "Texture detail", aspect: "square" },
      { src: "/portfolio/ama-shea-6-square.jpg", alt: "Collection", aspect: "square" },
      { src: "/portfolio/ama-shea-7-square.jpg", alt: "Brand lifestyle", aspect: "square" },
    ],
  },
];

export function Portfolio() {
  const [lightbox, setLightbox] = useState<{ src: string; alt: string } | null>(null);
  const gridRef = useRef<HTMLDivElement>(null);
  const gridProgress = useScrollProgress(gridRef);

  return (
    <section id="portfolio">
      {/* Scroll frame animation */}
      <ScrollFrameCanvas
        framePath="/frames/portfolio/frame-"
        frameCount={144}
        scrollHeight="200vh"
        fallbackSrc="/portfolio/nike-3-square.jpg"
        ext="jpg"
      >
        <div className="h-full flex items-center justify-center">
          <div className="text-center relative">
            <div className="absolute inset-0 -m-8 rounded-3xl bg-background/40 backdrop-blur-sm" />
            <div className="relative">
              <p className="text-xs font-mono text-muted-foreground tracking-widest uppercase mb-4">
                Portfolio
              </p>
              <h2 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight">
                Real campaigns.
                <br />
                <span className="text-gradient-warm">Real output.</span>
              </h2>
              <p className="mt-6 text-lg text-muted-foreground max-w-md mx-auto">
                Every image generated by AI. No retouching, no Photoshop.
              </p>
            </div>
          </div>
        </div>
      </ScrollFrameCanvas>

      {/* Image grid */}
      <div ref={gridRef} className="py-32 sm:py-40">
        <div className="mx-auto max-w-7xl px-6">
          <div className="space-y-32">
            {caseStudies.map((study, idx) => (
              <motion.div
                key={study.brand}
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ duration: 0.8, delay: idx * 0.1 }}
              >
                {/* Header */}
                <div className="flex flex-col sm:flex-row sm:items-end justify-between mb-10 gap-4">
                  <div>
                    <div className="text-xs font-mono text-muted-foreground mb-2 tracking-widest uppercase">
                      {study.brand}
                    </div>
                    <h3 className="text-3xl font-bold">{study.campaign}</h3>
                    <p className="mt-3 text-muted-foreground max-w-lg text-sm">
                      {study.description}
                    </p>
                  </div>
                  <div className="flex gap-8">
                    {study.stats.map((stat) => (
                      <div key={stat.label} className="text-right">
                        <div className="text-xl font-bold">{stat.value}</div>
                        <div className="text-[10px] text-muted-foreground uppercase tracking-widest">
                          {stat.label}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Divider */}
                <div className="divider mb-10" />

                {/* Image grid */}
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                  {study.images.map((img, i) => (
                    <motion.button
                      key={img.src}
                      initial={{ opacity: 0, y: 20 }}
                      whileInView={{ opacity: 1, y: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: i * 0.06 }}
                      onClick={() => setLightbox(img)}
                      className={`relative overflow-hidden rounded-xl bg-muted group cursor-pointer hover-lift ring-1 ring-white/5 ${
                        img.aspect === "landscape"
                          ? "col-span-2 aspect-video"
                          : img.aspect === "story"
                          ? "aspect-[9/16] row-span-2"
                          : "aspect-square"
                      }`}
                    >
                      <Image
                        src={img.src}
                        alt={img.alt}
                        fill
                        className="object-cover transition-transform duration-700 group-hover:scale-105"
                        sizes="(max-width: 768px) 50vw, 25vw"
                      />
                      <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors duration-300" />
                    </motion.button>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>

      {/* Lightbox */}
      <AnimatePresence>
        {lightbox && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm p-4"
            onClick={() => setLightbox(null)}
          >
            <button
              onClick={() => setLightbox(null)}
              aria-label="Close lightbox"
              className="absolute top-6 right-6 text-white/50 hover:text-white transition-colors"
            >
              <X size={28} />
            </button>
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="relative max-w-4xl max-h-[85vh] w-full"
              onClick={(e) => e.stopPropagation()}
            >
              <Image
                src={lightbox.src}
                alt={lightbox.alt}
                width={1200}
                height={1200}
                className="w-full h-auto max-h-[85vh] object-contain rounded-lg"
              />
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}
